export const NAMES: [string, string, string][] = [
  ["الرَّحْمَٰن", "Ar-Rahman", "The Most Compassionate"],
  ["الرَّحِيم", "Ar-Rahim", "The Most Merciful"],
  ["الْمَلِك", "Al-Malik", "The King"],
  ["الْقُدُّوس", "Al-Quddus", "The Most Holy"],
  ["السَّلَام", "As-Salam", "The Source of Peace"],
  ["الْمُؤْمِن", "Al-Mu'min", "The Granter of Security"],
  ["الْمُهَيْمِن", "Al-Muhaymin", "The Guardian"],
  ["الْعَزِيز", "Al-Aziz", "The Almighty"],
  ["الْجَبَّار", "Al-Jabbar", "The Compeller"],
  ["الْمُتَكَبِّر", "Al-Mutakabbir", "The Supreme"],
  ["الْخَالِق", "Al-Khaliq", "The Creator"],
  ["الْبَارِئ", "Al-Bari'", "The Maker"],
  ["الْمُصَوِّر", "Al-Musawwir", "The Fashioner"],
  ["الْغَفَّار", "Al-Ghaffar", "The Ever-Forgiving"],
  ["الْقَهَّار", "Al-Qahhar", "The Subduer"],
  ["الْوَهَّاب", "Al-Wahhab", "The Bestower"],
  ["الرَّزَّاق", "Ar-Razzaq", "The Provider"],
  ["الْفَتَّاح", "Al-Fattah", "The Opener"],
  ["الْعَلِيم", "Al-Alim", "The All-Knowing"],
  ["الْقَابِض", "Al-Qabid", "The Withholder"],
  ["الْبَاسِط", "Al-Basit", "The Expander"],
  ["الْخَافِض", "Al-Khafid", "The Abaser"],
  ["الرَّافِع", "Ar-Rafi'", "The Exalter"],
  ["الْمُعِزّ", "Al-Mu'izz", "The Giver of Honor"],
  ["الْمُذِلّ", "Al-Mudhill", "The Humbler"],
  ["السَّمِيع", "As-Sami'", "The All-Hearing"],
  ["الْبَصِير", "Al-Basir", "The All-Seeing"],
  ["الْحَكَم", "Al-Hakam", "The Judge"],
  ["الْعَدْل", "Al-Adl", "The Just"],
  ["اللَّطِيف", "Al-Latif", "The Subtle"],
  ["الْخَبِير", "Al-Khabir", "The All-Aware"],
  ["الْحَلِيم", "Al-Halim", "The Forbearing"],
  ["الْعَظِيم", "Al-Azim", "The Magnificent"],
  ["الْغَفُور", "Al-Ghafur", "The Forgiving"],
  ["الشَّكُور", "Ash-Shakur", "The Appreciative"],
  ["الْعَلِيّ", "Al-Aliyy", "The Most High"],
  ["الْكَبِير", "Al-Kabir", "The Greatest"],
  ["الْحَفِيظ", "Al-Hafiz", "The Preserver"],
  ["الْمُقِيت", "Al-Muqit", "The Sustainer"],
  ["الْحَسِيب", "Al-Hasib", "The Reckoner"],
  ["الْجَلِيل", "Al-Jalil", "The Majestic"],
  ["الْكَرِيم", "Al-Karim", "The Generous"],
  ["الرَّقِيب", "Ar-Raqib", "The Watchful"],
  ["الْمُجِيب", "Al-Mujib", "The Responsive"],
  ["الْوَاسِع", "Al-Wasi'", "The All-Encompassing"],
  ["الْحَكِيم", "Al-Hakim", "The Wise"],
  ["الْوَدُود", "Al-Wadud", "The Loving"],
  ["الْمَجِيد", "Al-Majid", "The Glorious"],
  ["الْبَاعِث", "Al-Ba'ith", "The Resurrector"],
  ["الشَّهِيد", "Ash-Shahid", "The Witness"],
  ["الْحَقّ", "Al-Haqq", "The Truth"],
  ["الْوَكِيل", "Al-Wakil", "The Trustee"],
  ["الْقَوِيّ", "Al-Qawiyy", "The Strong"],
  ["الْمَتِين", "Al-Matin", "The Firm"],
  ["الْوَلِيّ", "Al-Waliyy", "The Protecting Friend"],
  ["الْحَمِيد", "Al-Hamid", "The Praiseworthy"],
  ["الْمُحْصِي", "Al-Muhsi", "The Accounter"],
  ["الْمُبْدِئ", "Al-Mubdi'", "The Originator"],
  ["الْمُعِيد", "Al-Mu'id", "The Restorer"],
  ["الْمُحْيِي", "Al-Muhyi", "The Giver of Life"],
  ["الْمُمِيت", "Al-Mumit", "The Bringer of Death"],
  ["الْحَيّ", "Al-Hayy", "The Ever-Living"],
  ["الْقَيُّوم", "Al-Qayyum", "The Self-Subsisting"],
  ["الْوَاجِد", "Al-Wajid", "The Finder"],
  ["الْمَاجِد", "Al-Majid", "The Noble"],
  ["الْوَاحِد", "Al-Wahid", "The One"],
  ["الْأَحَد", "Al-Ahad", "The Unique"],
  ["الصَّمَد", "As-Samad", "The Eternal"],
  ["الْقَادِر", "Al-Qadir", "The Able"],
  ["الْمُقْتَدِر", "Al-Muqtadir", "The Powerful"],
  ["الْمُقَدِّم", "Al-Muqaddim", "The Expediter"],
  ["الْمُؤَخِّر", "Al-Mu'akhkhir", "The Delayer"],
  ["الْأَوَّل", "Al-Awwal", "The First"],
  ["الْآخِر", "Al-Akhir", "The Last"],
  ["الظَّاهِر", "Az-Zahir", "The Manifest"],
  ["الْبَاطِن", "Al-Batin", "The Hidden"],
  ["الْوَالِي", "Al-Wali", "The Governor"],
  ["الْمُتَعَالِي", "Al-Muta'ali", "The Most Exalted"],
  ["الْبَرّ", "Al-Barr", "The Source of Goodness"],
  ["التَّوَّاب", "At-Tawwab", "The Acceptor of Repentance"],
  ["الْمُنْتَقِم", "Al-Muntaqim", "The Avenger"],
  ["الْعَفُوّ", "Al-Afuww", "The Pardoner"],
  ["الرَّءُوف", "Ar-Ra'uf", "The Kind"],
  ["مَالِكُ الْمُلْك", "Malik-ul-Mulk", "Owner of All Sovereignty"],
  ["ذُو الْجَلَالِ وَالْإِكْرَام", "Dhul-Jalali wal-Ikram", "Lord of Majesty and Honor"],
  ["الْمُقْسِط", "Al-Muqsit", "The Equitable"],
  ["الْجَامِع", "Al-Jami'", "The Gatherer"],
  ["الْغَنِيّ", "Al-Ghaniyy", "The Self-Sufficient"],
  ["الْمُغْنِي", "Al-Mughni", "The Enricher"],
  ["الْمَانِع", "Al-Mani'", "The Withholder"],
  ["الضَّارّ", "Ad-Darr", "The Distresser"],
  ["النَّافِع", "An-Nafi'", "The Benefiter"],
  ["النُّور", "An-Nur", "The Light"],
  ["الْهَادِي", "Al-Hadi", "The Guide"],
  ["الْبَدِيع", "Al-Badi'", "The Originator"],
  ["الْبَاقِي", "Al-Baqi", "The Everlasting"],
  ["الْوَارِث", "Al-Warith", "The Inheritor"],
  ["الرَّشِيد", "Ar-Rashid", "The Guide to the Right Path"],
  ["الصَّبُور", "As-Sabur", "The Patient"],
];

export type Dua = { id: string; tag: string; title: string; ar: string; en: string };

export const DUAS: Dua[] = [
  { id: "eat", tag: "food", title: "Before eating", ar: "بِسْمِ اللَّهِ", en: "In the name of Allah." },
  {
    id: "ate",
    tag: "food",
    title: "After eating",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    en: "Praise be to Allah who fed me this and provided it without any might or power from myself.",
  },
  {
    id: "leave-home",
    tag: "home",
    title: "Leaving home",
    ar: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    en: "In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.",
  },
  {
    id: "enter-home",
    tag: "home",
    title: "Entering home",
    ar: "بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    en: "In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we rely.",
  },
  {
    id: "enter-masjid",
    tag: "mosque",
    title: "Entering the mosque",
    ar: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    en: "O Allah, open for me the doors of Your mercy.",
  },
  {
    id: "leave-masjid",
    tag: "mosque",
    title: "Leaving the mosque",
    ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    en: "O Allah, I ask You of Your bounty.",
  },
  {
    id: "morning",
    tag: "day",
    title: "Morning",
    ar: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
    en: "We have reached the morning and the dominion belongs to Allah, and all praise is for Allah.",
  },
  {
    id: "evening",
    tag: "day",
    title: "Evening",
    ar: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
    en: "We have reached the evening and the dominion belongs to Allah, and all praise is for Allah.",
  },
  {
    id: "sleep",
    tag: "night",
    title: "Before sleep",
    ar: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    en: "In Your name, O Allah, I die and I live.",
  },
  {
    id: "wake",
    tag: "night",
    title: "On waking",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    en: "Praise be to Allah who gave us life after causing us to die, and to Him is the resurrection.",
  },
  {
    id: "toilet",
    tag: "home",
    title: "Entering the washroom",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
    en: "O Allah, I seek refuge in You from evil.",
  },
  {
    id: "after-salah",
    tag: "prayer",
    title: "After the prayer",
    ar: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
    en: "O Allah, You are Peace and from You is peace. Blessed are You, Owner of majesty and honor.",
  },
  {
    id: "kursi",
    tag: "prayer",
    title: "Ayat al-Kursi",
    ar: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    en: "Allah — there is no god except Him, the Ever-Living, the Self-Subsisting. Neither drowsiness nor sleep overtakes Him. To Him belongs whatever is in the heavens and whatever is on the earth. Who can intercede with Him except by His permission? He knows what is ahead of them and what is behind them, and they grasp nothing of His knowledge except what He wills. His Kursi extends over the heavens and the earth, and keeping them does not tire Him. And He is the Most High, the Magnificent.",
  },
  {
    id: "sayyid",
    tag: "forgiveness",
    title: "Sayyid al-Istighfar",
    ar: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    en: "O Allah, You are my Lord. There is no god except You. You created me and I am Your servant, and I keep Your covenant and promise as much as I can. I seek refuge in You from the evil of what I have done. I admit Your favor upon me and I admit my sin, so forgive me. No one forgives sins except You.",
  },
  {
    id: "istighfar",
    tag: "forgiveness",
    title: "Istighfar",
    ar: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
    en: "I seek Allah's forgiveness and I turn to Him in repentance.",
  },
  {
    id: "travel",
    tag: "travel",
    title: "Starting a journey",
    ar: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى",
    en: "O Allah, we ask You on this journey of ours for righteousness, piety, and deeds that please You.",
  },
];

export const PHRASES: { ar: string; en: string }[] = [
  { ar: "سُبْحَانَ اللَّهِ", en: "Subhan Allah" },
  { ar: "الْحَمْدُ لِلَّهِ", en: "Alhamdulillah" },
  { ar: "اللَّهُ أَكْبَرُ", en: "Allahu Akbar" },
  { ar: "لَا إِلَٰهَ إِلَّا اللَّهُ", en: "La ilaha illa Allah" },
  { ar: "أَسْتَغْفِرُ اللَّهَ", en: "Astaghfirullah" },
  { ar: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", en: "Subhan Allah wa bihamdihi" },
  { ar: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", en: "La hawla wa la quwwata illa billah" },
];
